# Generated by Django 6.0 on 2025-12-29 13:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(help_text='URL-friendly version of title', unique=True)),
                ('level', models.CharField(choices=[('+2', '+2 Level'), ('bachelor', 'Bachelor Level'), ('master', 'Master Level')], max_length=20)),
                ('description', models.TextField(blank=True, help_text='Course description shown on website')),
                ('thumbnail', models.ImageField(blank=True, help_text='Optional course thumbnail image', null=True, upload_to='course_thumbnails/')),
                ('display_order', models.IntegerField(default=0, help_text='Order in which courses appear (lower number = first)')),
                ('is_active', models.BooleanField(default=True, help_text='Uncheck to hide course from website')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['display_order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(help_text='URL-friendly version of title')),
                ('description', models.TextField(blank=True, help_text='Subject description')),
                ('display_order', models.IntegerField(default=0, help_text='Order in which subjects appear (lower number = first)')),
                ('is_active', models.BooleanField(default=True, help_text='Uncheck to hide subject from website')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(help_text='Select which course this subject belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='notes.course')),
            ],
            options={
                'ordering': ['display_order', 'title'],
                'unique_together': {('course', 'slug')},
            },
        ),
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(help_text='URL-friendly version of title')),
                ('content', models.TextField(blank=True, help_text='Chapter content (text only for now)')),
                ('display_order', models.IntegerField(default=0, help_text='Order in which chapters appear (lower number = first)')),
                ('is_active', models.BooleanField(default=True, help_text='Uncheck to hide chapter from website')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subject', models.ForeignKey(help_text='Select which subject this chapter belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='notes.subject')),
            ],
            options={
                'ordering': ['display_order', 'title'],
                'unique_together': {('subject', 'slug')},
            },
        ),
    ]
