# Generated by Django 6.0 on 2026-01-02 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_course_subject_chapter'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='pdf_file',
            field=models.FileField(blank=True, help_text='Upload PDF file for this chapter', null=True, upload_to='chapter_pdfs/'),
        ),
        migrations.AddField(
            model_name='chapter',
            name='video_url',
            field=models.URLField(blank=True, help_text='Enter Google Drive/YouTube video link', null=True),
        ),
    ]
