# Generated by Django 6.0 on 2026-01-02 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0003_chapter_pdf_file_chapter_video_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='pdf_file',
            field=models.FileField(blank=True, help_text='Upload PDF file for this chapter', null=True, upload_to=''),
        ),
    ]
