# Generated by Django 6.0 on 2026-01-08 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0005_userprofile_is_premium_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='email',
            field=models.EmailField(default='unknown@example.com', max_length=254),
        ),
    ]
